#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

root="$(cd "$(dirname "$0")/.."; pwd)"

if [ $# -eq 0 ]; then
  cd "$root" && script/run luacheck . .luacheckrc .busted
else
  "$root/script/run" luacheck "$@"
fi
