name: tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7.0
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Install Redis
        run: |
          sudo snap install redis
          sudo snap alias redis.cli redis-cli

      - name: Print Redis version
        run: redis-cli --version

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Lua
        uses: leafo/gh-actions-lua@v9

      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-luarocks
          path: .luarocks

      - name: Set up dependencies
        run: script/setup

      - name: Run tests
        run: script/test
